version: '3.0'

services:
  node:
#    build:
#      context: .
    image: vlakam/extra-chat-bot
    env_file: .env
    restart: always
    depends_on:
      - mongo
    networks:
      - database_nw

  mongo:
    restart: always
    image: mongo:latest
    volumes:
      - mongo-volume:/data/db
#    ports:
#      - 27017:27017
    networks:
      - database_nw

volumes:
  mongo-volume:
    driver: 'local'

networks:
  database_nw:
    driver: bridge
